#!/bin/bash

if [ "$TRAVIS_BRANCH" == "develop" ] || [ "$TRAVIS_BRANCH" == "feature/travis-support" ]; then
  ENV=test;
elif [ "$TRAVIS_PULL_REQUEST" == false ] && [ "$TRAVIS_BRANCH" == "master" ]; then
  ENV=prod;
else
  unset ENV;
fi

IMAGE_NAME="eu.gcr.io/marine-cycle-97212/floq-reports-api"

if ! [ -z "$ENV" ]; then
  TAG="$ENV-$TRAVIS_COMMIT";
  docker login --username="$DOCKER_USER" --password="$DOCKER_PASS";
  docker tag floq-reports-api "$IMAGE_NAME:$TAG";
  gcloud docker -- push "$IMAGE_NAME:$TAG";
  docker tag floq-reports-api "$IMAGE_NAME:$ENV";
  gcloud docker -- push "$IMAGE_NAME:$ENV";
  export GOOGLE_APPLICATION_CREDENTIALS="${PWD}/client-secret.json";
  "$HOME/google-cloud-sdk/bin/kubectl" \
    set image deployment/floq-reports-api \
    --namespace=floq-blank-$ENV \
    "floq-reports-api=$IMAGE_NAME:$TAG";
fi
